name: secret-manager
on: [push]
jobs:
     deploy:
         runs-on: ubuntu-latest
         steps:
         - name: echo
           run: echo "GKEMHCS"
         - name:  json 
           run : echo ${{ toJson(github) }}
         - name: print 
           run: echo ${{ github.actor }}
                  

