name: secret-manager
on:
    push:
       branches:
       - main 
jobs:
     deploy:
         runs-on: ubuntu-18.04
         steps:
         - name: echo
           run: echo "GKEMHCS"
         - name:  json 
           run : echo ${{ tojson(github) }}
                  

