name: production-workflow
on: push
run-name: production-runner 
jobs:
   secrets-list:
      runs-on: ubuntu-latest
      permissions:
        contents: 'read'
        id-token: 'write'
      environment: development
      steps:
      - name: google auth 
        uses: 'google-github-actions/auth@v0'
        with:
           workload_identity_provider: '${{ secrets.WF_POOL }}'
           service_account: '${{secrets.WF_SA  }}'
      - name: set up google cloud sdk 
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
            version: '>= 363.0.0'
            project_id: github-actions-demo-run
            install_components: 'gsutil'
      - name: google cloud secrets list 
        run:  gcloud secrets list