name: production-workflow
on: push
run-name: production-runner 
jobs:
   secrets-list:
      
      runs-on: ubuntu-latest
      permissions:
        contents: 'read'
        id-token: 'write'
      outputs:
        url: ${{steps.url-getter.outputs.url}}  
      environment: development
      steps:
      - name: google auth 
        uses: 'google-github-actions/auth@v0'
        with:
           workload_identity_provider: '${{ secrets.WF_POOL }}'
           service_account: '${{secrets.WF_SA  }}'
      - name: set up google cloud sdk 
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
            version: '>= 363.0.0'
            project_id: github-actions-demo-run
            install_components: 'gsutil'
      - name: get cloud run url 
        id: url-getter
        run: |
            export url=$(gcloud run services describe github-ci-cd --region us-central1 --format "value(status.address.url)")
            echo "url=${url}" > "$GITHUB_OUTPUT"
      - name: print url 
        run: echo ${{ steps.url-getter.outputs.url }}
   print_url:
       runs-on: ubuntu-latest
       needs:  [secrets-list]
       steps:
       - name: print 
         run: echo ${{ needs.secrets-list.outputs.url }}
